### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by jcarvin**
In order to fix some permission issues I had to add :z to the end of the mapped volume in the docker-compose file: `- .:/app:z` 
Let me know if that's an issue and, if so, how I can better handle it.

Also the docker container didn't come with rails installed. So you have to run `apt-get install -y rails` before you can start installing the bundle and yarn. Would it be okay to add that to the dockerfile?

### CODE REVIEW

**Comment by rwilcox** [comment]
~~So I though / envisoned the Vagrant environment as a VM where you could run Docker Compose. Then you can use the `dev-scripts/start_env.sh` to start the Docker containers for the app, and `dev-scripts/ssh_env.sh` to ssh into *that*.~~

Never mind that above, I see what you're saying.

When you ssh into the Docker container you need to go into the app directory and `bundle install`. Bundle should be installed, so that should pull down all the components you need.

Yarn should install itself, but I guess you could `npm install -g yarn`????

The volume permission thing is odd, but I don't have opinions about this.

**Comment by jcarvin** [comment]
Oh okay! I'm sorry. I don't know what I was doing that it wasn't working. But it's all running smoothly now. No changes needed. 

Will the compose file still run for you with the `:z` appended to the mapped volume?

**Comment by rwilcox** [comment]
I will pull down the branch and try it tonight: it shouldn't, but I also haven't seen that syntax before so yay learning!

**Comment by rwilcox** [comment]
Ok, I'm going to follow up on something because I guess here is an OK place to that.

First, you must have dug pretty hard to find the `:z`option. Took me 15 or 20 minutes of digging to find anything definitive about that. Eventually what I found boiled down to "a definitive enough sounding person on StackOverflow", which isn't great. (For my own future reference, the best I was able to find was https://stackoverflow.com/a/34537509/224334 )

I don't *think* this solves the permission problem of files created inside the container when you go to edit them outside the container being read only / owned by root. 

... in fact, it doesn't, at least for me. For the technical reason behind this, see this docker\compose\issues\1532 (manually replace \s with /s : I don't want Github mentioning this ticket in that ticket).

In fact, OS X and Linux Docker hosts are different this way: explaining why I run a Docker environment all day every day in OS X and work and don't see this, but *do* on my Ubuntu laptop.

I may play with solutions at some point in the near future (filing an issue in this repo so I look), but for now, if you are creating files in the Docker Container, and want to edit them on the host, you need to `sudo chown $USER whatever/file.rb` to change the ownership on it so you can edit it.

But good job

**Pull request merged**
