### PR TITLE
Vagrant setup

### PR DESCRIPTION
**Pull request by jcarvin**
I Set up a Vagrant machine so that I can run Docker on Windows without Hyper-V. 

## Setup
* First `cd` into the projects root directory and run `vagrant up`. The first time you run this command may take a minute or two. 

* When it's finished building the machine, run `vagrant ssh`. 

### Tips from inside the machine
* docker mush be run as sudo
* To keep all the files on your local machine up to date with the files in  your vagrant machine open a new console in the projects root directory and run `vagrant rsync-auto`
* If docker isn't working, your docker daemon probably isn't running. Exit the vagrant machine: `logout`, and run `vagrant provision`. When that has finished run `vagrant ssh` and docker should be working fine.

### CODE REVIEW

**Comment by rwilcox** [comment]
Neat! Good setup instructions, please add that to the README. Maybe separate them out, "Running Docker" and "Running Docker in Vagrant" ??

**Comment by rwilcox** [comment]
That rebase went... weird. (I'm not sure how to fix - I have a pretty big distrust of all but the most simple rebasing)

can you branch off master, and `git cherry-pick` your (4) commits from the `vagrant_setup` branch into the new branch? Make the one change I wanted, do another PR, we'll close this one.

Else I'm worried we'd have my commits repeated, which will look weird in the history...

**Comment by jcarvin** [comment]
Oh man. Yeah I'll get it fixed up asap. Sorry about that.

**Comment by jcarvin** [comment]
Replaced this branch with `vagrant` 3bec715

**Pull request closed without merging**
